export const Colors = {
  light: {
    background: "#F5F9F6",
    surface: "#FFFFFF",
    surfaceAlt: "#EEF5F0",
    primary: "#1A7A3C",
    primaryDark: "#0F5228",
    red: "#E53935",
    primaryLight: "#D4EDDA",
    accent: "#4CAF73",
    accentAlt: "#F0A500",
    text: "#0D1F14",
    textSecondary: "#4A6355",
    textMuted: "#8DA899",
    border: "#C8DDD1",
    cardShadow: "rgba(26, 122, 60, 0.10)",
    electricBadge: "#1A7A3C",
    hybridBadge: "#1565C0",
    tabBar: "#FFFFFF",
    tabBarActive: "#1A7A3C",
    tabBarInactive: "#8DA899",
    statusBar: "dark",
    mapStyle: [],
  },
  dark: {
    background: "#0A1410",
    surface: "#111D16",
    surfaceAlt: "#162118",
    primary: "#4CAF73",
    primaryDark: "#3A8F5C",
    primaryLight: "#1A3D25",
    accent: "#6DD98A",
    accentAlt: "#FFB800",
    text: "#E8F5EC",
    textSecondary: "#9DC4AA",
    textMuted: "#5A7A65",
    border: "#1E3527",
    cardShadow: "rgba(0,0,0,0.4)",
    electricBadge: "#4CAF73",
    hybridBadge: "#5B9BD5",
    tabBar: "#111D16",
    tabBarActive: "#4CAF73",
    tabBarInactive: "#5A7A65",
    statusBar: "light",
    mapStyle: [
      { elementType: "geometry", stylers: [{ color: "#0d1b12" }] },
      { elementType: "labels.text.fill", stylers: [{ color: "#6b9e79" }] },
      { elementType: "labels.text.stroke", stylers: [{ color: "#0d1b12" }] },
      {
        featureType: "road",
        elementType: "geometry",
        stylers: [{ color: "#162118" }],
      },
      {
        featureType: "water",
        elementType: "geometry",
        stylers: [{ color: "#071510" }],
      },
    ],
  },
};

export const Typography = {
  displayLarge: {
    fontSize: 32,
    fontWeight: "800" as const,
    letterSpacing: -0.5,
  },
  displayMedium: {
    fontSize: 26,
    fontWeight: "700" as const,
    letterSpacing: -0.3,
  },
  heading: { fontSize: 20, fontWeight: "700" as const, letterSpacing: -0.2 },
  subheading: { fontSize: 16, fontWeight: "600" as const },
  body: { fontSize: 15, fontWeight: "400" as const },
  bodySmall: { fontSize: 13, fontWeight: "400" as const },
  caption: { fontSize: 12, fontWeight: "500" as const, letterSpacing: 0.3 },
  label: { fontSize: 11, fontWeight: "700" as const, letterSpacing: 0.8 },
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
};

export const Radius = {
  sm: 8,
  md: 14,
  lg: 20,
  xl: 28,
  full: 999,
};
